### ISSUE TITLE
Exception when closing the game window

### ISSUE THREAD

**Issue by ghost** [shawn42/snelps#2]
./input_manager.rb:37:in `raise': exception class/object expected (TypeError)
    from ./input_manager.rb:37:in`main_loop'
    from /var/lib/gems/1.8/gems/rubygame-2.6.2/lib/rubygame/queue.rb:110:in `_old_each'
    from /var/lib/gems/1.8/gems/rubygame-2.6.2/lib/rubygame/queue.rb:110:in`each'
    from ./input_manager.rb:26:in `main_loop'
    from ./input_manager.rb:25:in`loop'
    from ./input_manager.rb:25:in `main_loop'
    from ./input_manager.rb:24:in`catch'
    from ./input_manager.rb:24:in `main_loop'
    from app.rb:55:in`main_loop'
    from app.rb:71:in `run'
    from app.rb:89

**Comment by shawn42** [comment]
This is an issue with closing any running rubygame window; closing this issue; writing up in rubygame
