### ISSUE TITLE
Add a redirection to this repo from the old Google Code one

### ISSUE THREAD

**Issue by akien-mga** [shawn42/snelps#7]
Snelps still has an old repo on Google Code (which will be closed sometime next year as the rest of the Google Code repos). It would be nice if you could add a mention on the front page that the project's official repo is now on GitHub.

**Comment by shawn42** [comment]
:+1: 
Done.  Thanks. I'm not actively developing Snelps, but how did you hear about it?

**Comment by akien-mga** [comment]
Actually I'm browsing through Google Code to archive unmaintained but worthy games repos here: https://github.com/LibreGameArchive
I was about to export Snelps to GitHub too when I found that you had done it already :)

**Comment by shawn42** [comment]
Ah, that makes sense.  Thanks for the extra effort!
